spring:
  cloud:
    gateway:
      routes:
        - id: ClientService
          uri: http://localhost:8082
          predicates:
            - Path=/user/**,/venue/**,/vendor/**
          filters:
            - AuthenticationFilter

        - id: AuthenticationService
          uri: http://localhost:8085
          predicates:
            - Path=/auth/**

        - id: Management
          uri: http://localhost:9999
          predicates:
            - Path=/employee/**,/api/**
          filters:
            - AuthenticationFilter

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000,http://127.0.0.1:3001"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS

  application:
    name: GatewayEvent

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
